### ISSUE TITLE
how the hell can i fix this?

### ISSUE THREAD

**Issue by practicemedicine** [kolessios/source-instructor#2]
![image](https://user-images.githubusercontent.com/102203580/215264641-78f57513-076a-417a-9769-6c7b32de1bfa.png)

help im getting these errors after putting the source instructor codes into it
i am using hl2mp source code

**Comment by PracticeMedicine03** [comment]
i am using

**Comment by practicemedicine** [comment]
i am still having problems rn

**Comment by Tuxxego** [comment]
I might give a fixed version soon

**Comment by practicemedicine** [comment]
alr

**Comment by practicemedicine** [comment]
damn does this repo not in dev?

**Comment by practicemedicine** [comment]
issue fixed! `utlsymbol.h` isn't supposed to be replaced in the first place
